/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'notice' : IDL.Null,
  'govtJob' : IDL.Null,
  'update' : IDL.Null,
});
export const Time = IDL.Int;
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'datePosted' : Time,
  'category' : Category,
});

export const idlService = IDL.Service({
  'addNotification' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
  'deleteNotification' : IDL.Func([IDL.Nat], [], []),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getNotification' : IDL.Func([IDL.Nat], [IDL.Opt(Notification)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'notice' : IDL.Null,
    'govtJob' : IDL.Null,
    'update' : IDL.Null,
  });
  const Time = IDL.Int;
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'datePosted' : Time,
    'category' : Category,
  });
  
  return IDL.Service({
    'addNotification' : IDL.Func([IDL.Text, IDL.Text, Category], [IDL.Nat], []),
    'deleteNotification' : IDL.Func([IDL.Nat], [], []),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getNotification' : IDL.Func([IDL.Nat], [IDL.Opt(Notification)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };